"""Pipeline configuration constants."""

import os

PIPELINE_VERSION = "0.1.0"

SCORING_WEIGHT_TEXT_SIMILARITY = float(os.environ.get("SCORING_WEIGHT_TEXT_SIMILARITY", "0.40"))
SCORING_WEIGHT_SKILL_MATCH = float(os.environ.get("SCORING_WEIGHT_SKILL_MATCH", "0.35"))
SCORING_WEIGHT_EXPERIENCE_FIT = float(os.environ.get("SCORING_WEIGHT_EXPERIENCE_FIT", "0.25"))

TFIDF_MAX_FEATURES = 5000
TFIDF_NGRAM_RANGE = (1, 2)
CALLBACK_RETRY_ATTEMPTS = 3
CALLBACK_RETRY_BACKOFF = [1, 5, 15]
SPACY_MODEL = os.environ.get("SPACY_MODEL", "en_core_web_md")
